name: Build Linux Package (No Titlebar)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  GIT_CONFIG_PARAMETERS: "'advice.defaultBranchName=false' 'init.defaultBranch=main'"
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: "true"
  CARGO_INCREMENTAL: "0"
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "16"

jobs:
  build-linux-x86_64:
    name: Build Linux x86_64 (No Titlebar)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup sccache
        uses: mozilla/sccache-action@v0.0.9
        with:
          version: "v0.10.0"

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: "false"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo-about
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-about@0.8.2

      - name: Install System Dependencies
        run: |
          ./script/linux

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.97.1
          targets: wasm32-wasip2, wasm32-unknown-unknown

      - name: Build Zed Release Package
        env:
          CC: clang
          CXX: clang++
        run: |
          ./script/bundle-linux

      - name: Upload Linux Package Artifact
        uses: actions/upload-artifact@v7
        with:
          name: zed-linux-x86_64-no-titlebar
          path: target/release/zed-linux-x86_64.tar.gz
          if-no-files-found: warn
